### ISSUE TITLE
Erro - Caso teste em Árvore Binária

### ISSUE THREAD

**Issue by GMLF** [rgmantovani/dataStructures#17]
Boa tarde,

Encontrei um erro no arquivo de saída 2 da atividade, pois a mesma pontua que a palavra “Brasil ou brasil” aparece na página 5 porem a mesma não se encontra no arquivo de entrada 2.  Seguem abaixo as imagens que correspondem ao erro.

Atenciosamente Guilherme Moreira.

![image](https://user-images.githubusercontent.com/55238444/128570698-59cea931-dc25-49e9-a887-987ebe56cf77.png)
![image](https://user-images.githubusercontent.com/55238444/128570702-8840b8a1-1d71-4b92-971c-7754a7ea1bd0.png)

**Comment by GMLF** [comment]
Boa tarde,

Encontrei outro erro no arquivo de saída 3, pois o mesmo consta a palavra “significado” ao invés da palavra “significados” como consta no arquivo de entrada. Seguem abaixo as imagens.

Entrada
![image](https://user-images.githubusercontent.com/55238444/128571209-393c3ab5-1d04-40c3-adb6-f59565aef0a2.png)
Saída
![image](https://user-images.githubusercontent.com/55238444/128571240-2bdf2512-31aa-4396-b5ac-d02831c206e6.png)


Atenciosamente Guilherme Moreira.

**Comment by rgmantovani** [comment]
Valeus Djongs ... averiguarei

**Comment by rgmantovani** [comment]
@GMLF no arquivo aqui: https://github.com/rgmantovani/dataStructures/blob/master/activities/at03_binaryTrees/tests/saida2.txt
já está a saída correta com brasil 4, 7. Provável que a versão do Moodle que está errada.

**Comment by rgmantovani** [comment]
O segundo erro eu arrumei aqui: https://github.com/rgmantovani/dataStructures/commit/d7970014df050569951a10ddf65a5d7fe407a8ea

Obrigado.
